# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gustavopiovesan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: asynchronous-report-generation-aws

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  memorySize: 128
  environment:
    DYNAMO_LEADS_TABLE: !Ref LeadsTable
    SQS_GENERATE_REPORT_QUEUE: !Ref GenerateReportQueue
    S3_REPORTS_BUCKET_NAME: !Ref ReportsBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: !GetAtt LeadsTable.Arn
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: !GetAtt GenerateReportQueue.Arn
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:AbortMultipartUpload
          Resource:
            - !GetAtt ReportsBucket.Arn
            - !Join ['/', [!GetAtt ReportsBucket.Arn, '*']]

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  populateDynamo:
    handler: src/functions/http/populateDynamo.handler
    timeout: 25
    events:
      - httpApi:
          path: /populate-dynamo
          method: POST
  generateReport:
    handler: src/functions/http/generateReport.handler
    events:
      - httpApi:
          path: /generate-report
          method: POST
  processReport:
    handler: src/functions/queues/processReport.handler
    timeout: 180
    events:
      - sqs:
          arn: !GetAtt GenerateReportQueue.Arn
          batchSize: 1

resources:
  - ${file(./resources/dynamodb/LeadsTable.yml)}
  - ${file(./resources/sqs/GenerateReportQueue.yml)}
  - ${file(./resources/s3/ReportsBucket.yml)}
