export const env = {
  DYNAMO_LEADS_TABLE: process.env.DYNAMO_LEADS_TABLE,
  SQS_GENERATE_REPORT_QUEUE: process.env.SQS_GENERATE_REPORT_QUEUE,
  S3_REPORTS_BUCKET_NAME: process.env.S3_REPORTS_BUCKET_NAME,
};
