Resources:
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: reports-bucket-gustavo-piovesan
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 1
          - Id: DeleteOldMultiPartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
